name: Generate Props Overview

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TSCIRCUIT_BOT_GITHUB_TOKEN }}

      - name: Setup bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate Props Overview
        run: bun scripts/generate-props-overview.ts

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: Update generated props overview"
          branch: ${{ github.ref }}
          commit_user_name: tscircuitbot
          commit_user_email: tscircuitbot@users.noreply.github.com
          commit_author: tscircuitbot <tscircuitbot@users.noreply.github.com>
